# add to designer-ci build.yml
# https://github.com/aditosoftware/adito-designer-ci/blob/main/.github/workflows/build.yml





# UITests on all plattforms in parallel
  ui_test:
    runs-on: ${{ matrix.os }}
    name: UI Tests
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
    steps:
    
      # Persist github actions
      - name: Github Action Cache
        uses: actions/cache@v3
        id: github-cache
        with:
          enableCrossOsArchive: true
          path: ./.github
          key: gh-build-${{ github.run_id }}-${{ github.run_number }}

      - name: Specify Build Cache
        uses: actions/cache@v3
        id: build-cache
        with:
          enableCrossOsArchive: true
          path: |
            ./*
            ~/.m2/repository/de/adito
          key: build-${{ github.run_id }}-${{ github.run_number }}
      
      # Check if action exists
      - name: Check Action Exists
        id: check_action_exists
        uses: andstor/file-existence-action@v2
        with:
          files: ".github/workflows/uitest-action, application/designer/target"
      
      # Execute Action
      - name: UI Tests
        if: steps.check_action_exists.outputs.files_exists == 'true'
        uses: ./.github/workflows/uitest-action
