name: "Execute UI Tests"
description: "Executes all ui tests" # needs license & ADITOdesigner.conf in QF-Test folder
runs:
  using: "composite"
  env:
    qfversion: '6.0.4'
    scaleuiwin: '-J-Dsun.java2d.dpiaware=true'
    scaleuilin: ''
    fullVersion: '1234.5.6.7'
  steps:
    
    # download qfs
    - name: download qftest-sfx.exe (win)
      if: runner.os == 'Windows'
      working-directory: ./QF-TestF
      shell: pwsh
      run: Invoke-WebRequest https://www.qfs.de/fileadmin/Webdata/pub/qftest/QF-Test-${{ env.qfversion }}-sfx.exe -OutFile qftest-sfx.exe
    
    
    - name: download qftest.tar.gz (lin)
      if: runner.os == 'Linux'
      working-directory: ./QF-Test
      shell: bash
      run: curl -o qftest.tar.gz "https://www.qfs.de/fileadmin/Webdata/pub/qftest/QF-Test-${{ env.qfversion }}.tar.gz"
    
    
####
    
    # install qfs
    - name: install qfs (win)
      if: runner.os == 'Windows'
      working-directory: ./QF-Test
      shell: cmd
      run: qftest-sfx.exe
    
    
    - name: install qfs (lin)
      if: runner.os == 'Linux'
      working-directory: ./QF-Test
      shell: bash
      run:  |
        tar xzvf qftest.tar.gz
        cd qftest/qftest-${{ env.qfversion }}
        printf 'y\ny\n1024\ng\n' | ./setup.sh
    
        
####    
    
    # edit ADITOdesigner.conf & move ADITOdesigner.conf + license to the right directory
    - name: ADITOdesigner.conf (win)
      if: runner.os == 'Windows'
      shell: pwsh
      run: (Get-Content QF-Test\ADITOdesigner.conf) | % {
             $_ -replace 'SCALEUI', '${{ env.scaleuiwin }}' `
                -replace 'FINALVERSION', '${{ env.fullVersion }}' `
                -replace 'jdkhome="jre"', 'jdkhome="${{ env.JAVA_HOME }}"' `
                -replace 'BASEPATH/lib/designer', '${{ github.workspace }}/application/designer/target/aditodesigner' `
                -replace 'BASEPATH', '${{ github.workspace }}' `
             } | Set-Content QF-Test\ADITOdesigner.conf; `
             Move-Item -Path QF-Test\ADITOdesigner.conf -Destination application\designer\target\aditodesigner\etc -Force; `
             Move-Item -Path QF-Test\license -Destination QF-Test\qftest\qftest-${{ env.qfversion }} -Force
      
    
    - name: ADITOdesigner.conf (lin)
      if: runner.os == 'Linux'
      shell: bash
      run:  |
        sed -i 's!SCALEUI!${{ env.scaleuilin }}!g' QF-Test/ADITOdesigner.conf
        sed -i 's!FINALVERSION!${{ env.fullVersion }}!g' QF-Test/ADITOdesigner.conf
        sed -i 's!jdkhome="jre"!jdkhome="${{ env.JAVA_HOME }}"!g' QF-Test/ADITOdesigner.conf
        sed -i 's!BASEPATH/lib/designer!${{ github.workspace }}/application/designer/target/aditodesigner!g' QF-Test/ADITOdesigner.conf
        sed -i 's!BASEPATH!${{ github.workspace }}!g' QF-Test/ADITOdesigner.conf
        mv -f QF-Test/ADITOdesigner.conf application/designer/target/aditodesigner/etc
        mv -f QF-Test/license QF-Test/qftest/qftest-${{ env.qfversion }}
    
    
####
    
    # execute ui tests
    - name: UI Tests (win)
      if: runner.os == 'Windows'
      working-directory: ./QF-Test
      shell: cmd
      run: qftest\qftest-${{ env.qfversion }}\bin\qftestc.exe -batch -nomessagewindow -verbose -run testsuites\exampleTestSuiteDesigner.qft
    
    - name: UI Tests (lin)
      if: runner.os == 'Linux'
      working-directory: ./QF-Test
      shell: bash
      run: qftest/qftest-${{ env.qfversion }}/bin/qftest -batch -nomessagewindow -verbose -run testsuites/exampleTestSuiteDesigner.qft
    
