on:
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
    env:
      qfversion: '6.0.4'
    steps:
    
    
    - name: check github env (win)
      if: runner.os == 'Windows'
      shell: cmd
      working-directory: ./QF-Test
      run: echo %GITHUB_WORKSPACE%
    
    - name: check github env (lin)
      if: runner.os == 'Linux'
      shell: bash
      working-directory: ./QF-Test
      run: echo $GITHUB_WORKSPACE
    
    - name: check github env (mac)
      if: runner.os == 'macOS'
      shell: bash
      working-directory: ./QF-Test
      run: echo $GITHUB_WORKSPACE
    
