on:
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
    env:
      qfversion: '6.0.4'
    steps:
    
    - name: checkout repo
      uses: actions/checkout@v3
      
    - name: checkout quick-download
      uses: actions/checkout@v3
      with:
        repository: 2Akuma2/quick-download
        path: './quick-download'
    
    - name: download qfs-sfx.exe (win)
      if: runner.os == 'Windows'
      uses: ./quick-download
      with:
        source_url: https://www.qfs.de/fileadmin/Webdata/pub/qftest/QF-Test-$qfversion-sfx.exe
        output_path: ./QF-Test
        output_file: qftest.exe
    
    - name: download qfs.tar (lin)
      if: runner.os == 'Linux'
      uses: ./quick-download
      with:
        source_url: https://www.qfs.de/fileadmin/Webdata/pub/qftest/QF-Test-$qfversion.tar.gz
        output_path: ./QF-Test
        output_file: qftest.tar.gz
    
    - name: download qfs.dmg (mac)
      if: runner.os == 'macOS'
      uses: ./quick-download
      with:
        source_url: https://www.qfs.de/fileadmin/Webdata/pub/qftest/QF-Test-$qfversion.dmg
        output_path: ./QF-Test
        output_file: qftest.dmg

    - name: test download
      shell: bash
      working-directory: ./QF-Test
      run: curl -o qftest2.file https://www.qfs.de/fileadmin/Webdata/pub/qftest/QF-Test-6.0.4-sfx.exe
      
    - name: check for download
      shell: bash
      working-directory: ./QF-Test
      run: ls 
